CREATE DATABASE IF NOT EXISTS weather_assistant;
USE weather_assistant;

CREATE TABLE IF NOT EXISTS weather_queries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    temperature DECIMAL(5,2) NOT NULL,
    weather_condition VARCHAR(100) NOT NULL,
    recommended_clothes TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(150) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE weather_queries MODIFY COLUMN id BIGINT AUTO_INCREMENT;
